<?php
# This file was automatically generated by the MediaWiki 1.17.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings


############ SC settings ############
$wgNamespacesWithSubpages[NS_MAIN] = true;


// can view deleted history entries, but not see or restore the text
$wgGroupPermissions['*']['deletedhistory'] = true;
// can view deleted revision text
$wgGroupPermissions['*']['deletedtext'] = true;
$wgGroupPermissions['*']['undelete'] = true;
$wgGroupPermissions['*']['editinterface'] = true;
$wgGroupPermissions['*']['editsitejson'] = true;
$wgGroupPermissions['*']['edituserjson'] = true;
$wgGroupPermissions['*']['import'] = true;
$wgGroupPermissions['*']['importupload'] = true;
$wgGroupPermissions['*']['move'] = true;
$wgGroupPermissions['*']['move-subpages'] = true;
$wgGroupPermissions['*']['move-rootuserpages'] = true;
$wgGroupPermissions['*']['move-categorypages'] = true;
$wgGroupPermissions['*']['patrol'] = true;
$wgGroupPermissions['*']['autopatrol'] = true;
$wgGroupPermissions['*']['protect'] = true;
$wgGroupPermissions['*']['editprotected'] = true;
$wgGroupPermissions['*']['rollback'] = true;
$wgGroupPermissions['*']['upload'] = true;
$wgGroupPermissions['*']['reupload'] = true;
$wgGroupPermissions['*']['reupload-shared'] = true;
$wgGroupPermissions['*']['unwatchedpages'] = true;
$wgGroupPermissions['*']['autoconfirmed'] = true;
$wgGroupPermissions['*']['editsemiprotected'] = true;
$wgGroupPermissions['*']['ipblock-exempt'] = true;
$wgGroupPermissions['*']['blockemail'] = true;
$wgGroupPermissions['*']['markbotedits'] = true;
$wgGroupPermissions['*']['apihighlimits'] = true;
$wgGroupPermissions['*']['browsearchive'] = true;
$wgGroupPermissions['*']['noratelimit'] = true;
$wgGroupPermissions['*']['movefile'] = true;
$wgGroupPermissions['*']['unblockself'] = true;
$wgGroupPermissions['*']['suppressredirect'] = true;
# $wgGroupPermissions['*']['pagelang'] = true;
# $wgGroupPermissions['*']['upload_by_url'] = true;
$wgGroupPermissions['*']['mergehistory'] = true;
$wgGroupPermissions['*']['managechangetags'] = true;
$wgGroupPermissions['*']['deletechangetags'] = true;

$wgAllowUserCss = true;
$wgAllowUserJs = true;
$wgGroupPermissions['*']['userrights'] = true;
$wgGroupPermissions['*']['masseditregex'] = true;
############ SC settings ############

$wgLocaltimezone = "America/New_York";




# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = "Steve Carol Personal Wiki";
$wgMetaNamespace = "user's Wiki!";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/wiki";
$wgScriptExtension  = ".php";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";
wfLoadSkin( 'Vector' );

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
#$wgLogo             = "$wgScriptPath/resources/assets/mediawiki.png";
$wgLogo             = "$wgScriptPath/resources/assets/book.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "user@example.com";
$wgPasswordSender   = "user@example.com";

$wgEnotifUserTalk      = false; # UPO
$wgEnotifWatchlist     = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost:3306";
$wgDBname           = "bitnami_mediawiki";
$wgDBuser           = "bn_mediawiki";
$wgDBpassword       = "6dad090786";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_NONE;
$wgMemCachedServers = array();

# Image Converter
$wgSVGConverter = 'ImageMagick';

# Image converter path
$wgSVGConverterPath = '/opt/bitnami/common/bin';

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/opt/bitnami/common/bin/convert";

# Path to jpegtran utility
$wgJpegTran = '/opt/bitnami/common/bin/';

# Path to tidy utility binary
$wgTidyBin = '/opt/bitnami/common/bin/';

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of ./languages/Language(.*).php
$wgLanguageCode = "en";

$wgSecretKey = "6796ae6e66b0f91448b7597e3127b0f42aa7bb72af96f5bbf42d049342d4612b";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "447d61b0064d094f";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
#$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";



# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;


# End of automatically generated settings.
# Add more configuration options below.

$wgArticlePath = "/wiki/$1";
$wgUsePathInfo = true;
$wgPhpCli = "/opt/bitnami/php/bin/php";

############ SC settings ############

wfLoadExtension( 'Cite' );
wfLoadExtension( 'MagicNoCache' );
wfLoadExtension( 'ParserFunctions' );
$wgPFEnableStringFunctions = true;
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'NumberedHeadings' );
wfLoadExtension( 'LabeledSectionTransclusion' );
#
# -- disabling Math to test MathJax extension--
# -- 20200218-2002
#wfLoadExtension( 'Math' );
#$wgUseTeX = true;
#$wgMathValidModes = array('png', 'source', 'mathml');
##wgMathDisableTexFilter = 'never';
#$wgDefaultUserOptions['math'] = 'mathml';
#$wgMathFullRestbaseURL = 'https://en.wikipedia.org/api/rest_';
#
wfLoadExtension( 'Variables' );
require_once "$IP/extensions/MassEditRegex/MassEditRegex.php";

#---------------------------------------
# -- for Graph (abandonded 20191031-1627)
#    -- JsonConfig
#wfLoadExtension( 'JsonConfig' );
#// Content model is 'JsonConfig.MySettings'
#// Model class is set to NULL to allow non-validated data
#$wgJsonConfigModels['JsonConfig.MySettings'] = null;
#
#$wgJsonConfigs['JsonConfig.MySettings'] = array('pattern' => '/^MySettings$/', // Page name in Config namespace);
##   -- Graph
#wfLoadExtension( 'Graph' );
#---------------------------------------

$wgAllowExternalImages = true;
$wgAllowImageTag = true;

#$wgEnableImageWhitelist = true;

#---------------------------------------
# -- for Popups
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'Popups' );
$wgPopupsHideOptInOnPreferencesPage = true;
$wgPopupsOptInDefaultState = '1';
$wgPopupsReferencePreviewsBetaFeature = false;
#---------------------------------------
$wgUseInstantCommons = true;
#--- MathJax ---------------------------
wfLoadExtension( 'MathJax' );
$wgAdvancedSearchHighlighting = true;
#Solution to "... problem with your login session ..." issue - webserver is not doing https
# see https://www.mediawiki.org/wiki/Topic:Tvx6bgsxmwktdye9
$wgCookieSecure = false;
############ SC settings ############
